let types = {
  FETCH_CURRENCIES: {
    REQUEST: 'FETCH_CURRENCIES_REQUEST',
    SUCCESS: 'FETCH_CURRENCIES_SUCCESS',
    FAILURE: 'FETCH_CURRENCIES_FAILURE',
  },
  FETCH_PAGE_SOURCE: {
    REQUEST: 'FETCH_PAGE_SOURCE_REQUEST',
    SUCCESS: 'FETCH_PAGE_SOURCE_SUCCESS',
    FAILURE: 'FETCH_PAGE_SOURCE_FAILURE',
  },
};

export default types;
